package upgrade.ntv.bangsoccer.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import upgrade.ntv.bangsoccer.dao.DBClubDao;
import upgrade.ntv.bangsoccer.dao.DBTourneyDao;
import upgrade.ntv.bangsoccer.dao.DBTeamDao;
import upgrade.ntv.bangsoccer.dao.DBMatchDao;
import upgrade.ntv.bangsoccer.dao.DBPlayerDao;
import upgrade.ntv.bangsoccer.dao.DBMatchesPlayerDetailsDao;
import upgrade.ntv.bangsoccer.dao.DBNewsFeedDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 4): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 4;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        DBClubDao.createTable(db, ifNotExists);
        DBTourneyDao.createTable(db, ifNotExists);
        DBTeamDao.createTable(db, ifNotExists);
        DBMatchDao.createTable(db, ifNotExists);
        DBPlayerDao.createTable(db, ifNotExists);
        DBMatchesPlayerDetailsDao.createTable(db, ifNotExists);
        DBNewsFeedDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        DBClubDao.dropTable(db, ifExists);
        DBTourneyDao.dropTable(db, ifExists);
        DBTeamDao.dropTable(db, ifExists);
        DBMatchDao.dropTable(db, ifExists);
        DBPlayerDao.dropTable(db, ifExists);
        DBMatchesPlayerDetailsDao.dropTable(db, ifExists);
        DBNewsFeedDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DBClubDao.class);
        registerDaoClass(DBTourneyDao.class);
        registerDaoClass(DBTeamDao.class);
        registerDaoClass(DBMatchDao.class);
        registerDaoClass(DBPlayerDao.class);
        registerDaoClass(DBMatchesPlayerDetailsDao.class);
        registerDaoClass(DBNewsFeedDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
