package upgrade.ntv.bangsoccer.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DBCLUB".
 */
public class DBClub {

    private Long id;
    /** Not-null value. */
    private String Name;
    private boolean Active;
    private String Stadium;
    private byte[] Logo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DBClub() {
    }

    public DBClub(Long id) {
        this.id = id;
    }

    public DBClub(Long id, String Name, boolean Active, String Stadium, byte[] Logo) {
        this.id = id;
        this.Name = Name;
        this.Active = Active;
        this.Stadium = Stadium;
        this.Logo = Logo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return Name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String Name) {
        this.Name = Name;
    }

    public boolean getActive() {
        return Active;
    }

    public void setActive(boolean Active) {
        this.Active = Active;
    }

    public String getStadium() {
        return Stadium;
    }

    public void setStadium(String Stadium) {
        this.Stadium = Stadium;
    }

    public byte[] getLogo() {
        return Logo;
    }

    public void setLogo(byte[] Logo) {
        this.Logo = Logo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
