package upgrade.ntv.bangsoccer.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DBFAVORITES".
 */
public class DBFavorites {

    private Long id;
    private String fb_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DBFavorites() {
    }

    public DBFavorites(Long id) {
        this.id = id;
    }

    public DBFavorites(Long id, String fb_id) {
        this.id = id;
        this.fb_id = fb_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFb_id() {
        return fb_id;
    }

    public void setFb_id(String fb_id) {
        this.fb_id = fb_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
