package upgrade.ntv.bangsoccer.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DBNEWS_FEED".
 */
public class DBNewsFeed {

    private Long id;
    private String Description;
    private byte[] Picture;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DBNewsFeed() {
    }

    public DBNewsFeed(Long id) {
        this.id = id;
    }

    public DBNewsFeed(Long id, String Description, byte[] Picture) {
        this.id = id;
        this.Description = Description;
        this.Picture = Picture;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public byte[] getPicture() {
        return Picture;
    }

    public void setPicture(byte[] Picture) {
        this.Picture = Picture;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
