package upgrade.ntv.bangsoccer.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DBSWITCH".
 */
public class DBSwitch {

    private Long id;
    private Boolean Status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DBSwitch() {
    }

    public DBSwitch(Long id) {
        this.id = id;
    }

    public DBSwitch(Long id, Boolean Status) {
        this.id = id;
        this.Status = Status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getStatus() {
        return Status;
    }

    public void setStatus(Boolean Status) {
        this.Status = Status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
